// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dentalclinic.Domain.Repository;

#nullable disable

namespace dentalclinic.Domain.Migrations
{
    [DbContext(typeof(DentalDBContext))]
    [Migration("20240811052531_db-1")]
    partial class db1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dentalclinic.Common.Model.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Moh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("Int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("UserRegNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRegNo"), 1L, 1);

                    b.Property<int>("UserTypeId")
                        .HasColumnType("Int");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserTypeId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("dentalclinic.Common.Model.Domain.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalityId"), 1L, 1);

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NationalityName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("NationalityId");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            NationalityId = 1,
                            IsActive = 1,
                            NationalityCode = "AF",
                            NationalityName = "AFGHANISTAN"
                        },
                        new
                        {
                            NationalityId = 2,
                            IsActive = 1,
                            NationalityCode = "AL",
                            NationalityName = "ALBANIA"
                        },
                        new
                        {
                            NationalityId = 3,
                            IsActive = 1,
                            NationalityCode = "DZ",
                            NationalityName = "ALGERIA"
                        },
                        new
                        {
                            NationalityId = 4,
                            IsActive = 1,
                            NationalityCode = "AS",
                            NationalityName = "AMERICAN SAMOA"
                        },
                        new
                        {
                            NationalityId = 5,
                            IsActive = 1,
                            NationalityCode = "AD",
                            NationalityName = "ANDORRA"
                        },
                        new
                        {
                            NationalityId = 6,
                            IsActive = 1,
                            NationalityCode = "AO",
                            NationalityName = "ANGOLA"
                        },
                        new
                        {
                            NationalityId = 7,
                            IsActive = 1,
                            NationalityCode = "AI",
                            NationalityName = "ANGUILLA"
                        },
                        new
                        {
                            NationalityId = 8,
                            IsActive = 1,
                            NationalityCode = "AQ",
                            NationalityName = "ANTARCTICA"
                        },
                        new
                        {
                            NationalityId = 9,
                            IsActive = 1,
                            NationalityCode = "AG",
                            NationalityName = "ANTIGUA AND BARBUDA"
                        },
                        new
                        {
                            NationalityId = 10,
                            IsActive = 1,
                            NationalityCode = "AR",
                            NationalityName = "ARGENTINA"
                        },
                        new
                        {
                            NationalityId = 11,
                            IsActive = 1,
                            NationalityCode = "AM",
                            NationalityName = "ARMENIA"
                        },
                        new
                        {
                            NationalityId = 12,
                            IsActive = 1,
                            NationalityCode = "AW",
                            NationalityName = "ARUBA"
                        },
                        new
                        {
                            NationalityId = 13,
                            IsActive = 1,
                            NationalityCode = "AU",
                            NationalityName = "AUSTRALIA"
                        },
                        new
                        {
                            NationalityId = 14,
                            IsActive = 1,
                            NationalityCode = "AT",
                            NationalityName = "AUSTRIA"
                        },
                        new
                        {
                            NationalityId = 15,
                            IsActive = 1,
                            NationalityCode = "AZ",
                            NationalityName = "AZERBAIJAN"
                        },
                        new
                        {
                            NationalityId = 16,
                            IsActive = 1,
                            NationalityCode = "BS",
                            NationalityName = "BAHAMAS"
                        },
                        new
                        {
                            NationalityId = 17,
                            IsActive = 1,
                            NationalityCode = "BH",
                            NationalityName = "BAHRAIN"
                        },
                        new
                        {
                            NationalityId = 18,
                            IsActive = 1,
                            NationalityCode = "BD",
                            NationalityName = "BANGLADESH"
                        },
                        new
                        {
                            NationalityId = 19,
                            IsActive = 1,
                            NationalityCode = "BB",
                            NationalityName = "BARBADOS"
                        },
                        new
                        {
                            NationalityId = 20,
                            IsActive = 1,
                            NationalityCode = "BY",
                            NationalityName = "BELARUS"
                        },
                        new
                        {
                            NationalityId = 21,
                            IsActive = 1,
                            NationalityCode = "BE",
                            NationalityName = "BELGIUM"
                        },
                        new
                        {
                            NationalityId = 22,
                            IsActive = 1,
                            NationalityCode = "BZ",
                            NationalityName = "BELIZE"
                        },
                        new
                        {
                            NationalityId = 23,
                            IsActive = 1,
                            NationalityCode = "BJ",
                            NationalityName = "BENIN"
                        },
                        new
                        {
                            NationalityId = 24,
                            IsActive = 1,
                            NationalityCode = "BM",
                            NationalityName = "BERMUDA"
                        },
                        new
                        {
                            NationalityId = 25,
                            IsActive = 1,
                            NationalityCode = "BT",
                            NationalityName = "BHUTAN"
                        },
                        new
                        {
                            NationalityId = 26,
                            IsActive = 1,
                            NationalityCode = "BO",
                            NationalityName = "BOLIVIA"
                        },
                        new
                        {
                            NationalityId = 27,
                            IsActive = 1,
                            NationalityCode = "BA",
                            NationalityName = "BOSNIA AND HERZEGOVINA"
                        },
                        new
                        {
                            NationalityId = 28,
                            IsActive = 1,
                            NationalityCode = "BW",
                            NationalityName = "BOTSWANA"
                        },
                        new
                        {
                            NationalityId = 29,
                            IsActive = 1,
                            NationalityCode = "BV",
                            NationalityName = "BOUVET ISLAND"
                        },
                        new
                        {
                            NationalityId = 30,
                            IsActive = 1,
                            NationalityCode = "BR",
                            NationalityName = "BRAZIL"
                        },
                        new
                        {
                            NationalityId = 31,
                            IsActive = 1,
                            NationalityCode = "IO",
                            NationalityName = "BRITISH INDIAN OCEAN TERRITORY"
                        },
                        new
                        {
                            NationalityId = 32,
                            IsActive = 1,
                            NationalityCode = "BN",
                            NationalityName = "BRUNEI DARUSSALAM"
                        },
                        new
                        {
                            NationalityId = 33,
                            IsActive = 1,
                            NationalityCode = "BG",
                            NationalityName = "BULGARIA"
                        },
                        new
                        {
                            NationalityId = 34,
                            IsActive = 1,
                            NationalityCode = "BF",
                            NationalityName = "BURKINA FASO"
                        },
                        new
                        {
                            NationalityId = 35,
                            IsActive = 1,
                            NationalityCode = "BI",
                            NationalityName = "BURUNDI"
                        },
                        new
                        {
                            NationalityId = 36,
                            IsActive = 1,
                            NationalityCode = "KH",
                            NationalityName = "CAMBODIA"
                        },
                        new
                        {
                            NationalityId = 37,
                            IsActive = 1,
                            NationalityCode = "CM",
                            NationalityName = "CAMEROON"
                        },
                        new
                        {
                            NationalityId = 38,
                            IsActive = 1,
                            NationalityCode = "CA",
                            NationalityName = "CANADA"
                        },
                        new
                        {
                            NationalityId = 39,
                            IsActive = 1,
                            NationalityCode = "CV",
                            NationalityName = "CAPE VERDE"
                        },
                        new
                        {
                            NationalityId = 40,
                            IsActive = 1,
                            NationalityCode = "KY",
                            NationalityName = "CAYMAN ISLANDS"
                        },
                        new
                        {
                            NationalityId = 41,
                            IsActive = 1,
                            NationalityCode = "CF",
                            NationalityName = "CENTRAL AFRICAN REPUBLIC"
                        },
                        new
                        {
                            NationalityId = 42,
                            IsActive = 1,
                            NationalityCode = "TD",
                            NationalityName = "CHAD"
                        },
                        new
                        {
                            NationalityId = 43,
                            IsActive = 1,
                            NationalityCode = "CL",
                            NationalityName = "CHILE"
                        },
                        new
                        {
                            NationalityId = 44,
                            IsActive = 1,
                            NationalityCode = "CN",
                            NationalityName = "CHINA"
                        },
                        new
                        {
                            NationalityId = 45,
                            IsActive = 1,
                            NationalityCode = "CX",
                            NationalityName = "CHRISTMAS ISLAND"
                        },
                        new
                        {
                            NationalityId = 46,
                            IsActive = 1,
                            NationalityCode = "CC",
                            NationalityName = "COCOS new Nationality{ NationalityId=KEELING) ISLANDS"
                        },
                        new
                        {
                            NationalityId = 47,
                            IsActive = 1,
                            NationalityCode = "CO",
                            NationalityName = "COLOMBIA"
                        },
                        new
                        {
                            NationalityId = 48,
                            IsActive = 1,
                            NationalityCode = "KM",
                            NationalityName = "COMOROS"
                        },
                        new
                        {
                            NationalityId = 49,
                            IsActive = 1,
                            NationalityCode = "CG",
                            NationalityName = "CONGO"
                        },
                        new
                        {
                            NationalityId = 50,
                            IsActive = 1,
                            NationalityCode = "CD",
                            NationalityName = "CONGO, THE DEMOCRATIC REPUBLIC OF THE"
                        },
                        new
                        {
                            NationalityId = 51,
                            IsActive = 1,
                            NationalityCode = "CK",
                            NationalityName = "COOK ISLANDS"
                        },
                        new
                        {
                            NationalityId = 52,
                            IsActive = 1,
                            NationalityCode = "CR",
                            NationalityName = "COSTA RICA"
                        },
                        new
                        {
                            NationalityId = 53,
                            IsActive = 1,
                            NationalityCode = "CI",
                            NationalityName = "COTE D'IVOIRE"
                        },
                        new
                        {
                            NationalityId = 54,
                            IsActive = 1,
                            NationalityCode = "HR",
                            NationalityName = "CROATIA"
                        },
                        new
                        {
                            NationalityId = 55,
                            IsActive = 1,
                            NationalityCode = "CU",
                            NationalityName = "CUBA"
                        },
                        new
                        {
                            NationalityId = 56,
                            IsActive = 1,
                            NationalityCode = "CY",
                            NationalityName = "CYPRUS"
                        },
                        new
                        {
                            NationalityId = 57,
                            IsActive = 1,
                            NationalityCode = "CZ",
                            NationalityName = "CZECH REPUBLIC"
                        },
                        new
                        {
                            NationalityId = 58,
                            IsActive = 1,
                            NationalityCode = "DK",
                            NationalityName = "DENMARK"
                        },
                        new
                        {
                            NationalityId = 59,
                            IsActive = 1,
                            NationalityCode = "DJ",
                            NationalityName = "DJIBOUTI"
                        },
                        new
                        {
                            NationalityId = 60,
                            IsActive = 1,
                            NationalityCode = "DM",
                            NationalityName = "DOMINICA"
                        },
                        new
                        {
                            NationalityId = 61,
                            IsActive = 1,
                            NationalityCode = "DO",
                            NationalityName = "DOMINICAN REPUBLIC"
                        },
                        new
                        {
                            NationalityId = 62,
                            IsActive = 1,
                            NationalityCode = "EC",
                            NationalityName = "ECUADOR"
                        },
                        new
                        {
                            NationalityId = 63,
                            IsActive = 1,
                            NationalityCode = "EG",
                            NationalityName = "EGYPT"
                        },
                        new
                        {
                            NationalityId = 64,
                            IsActive = 1,
                            NationalityCode = "SV",
                            NationalityName = "EL SALVADOR"
                        },
                        new
                        {
                            NationalityId = 65,
                            IsActive = 1,
                            NationalityCode = "GQ",
                            NationalityName = "EQUATORIAL GUINEA"
                        },
                        new
                        {
                            NationalityId = 66,
                            IsActive = 1,
                            NationalityCode = "ER",
                            NationalityName = "ERITREA"
                        },
                        new
                        {
                            NationalityId = 67,
                            IsActive = 1,
                            NationalityCode = "EE",
                            NationalityName = "ESTONIA"
                        },
                        new
                        {
                            NationalityId = 68,
                            IsActive = 1,
                            NationalityCode = "ET",
                            NationalityName = "ETHIOPIA"
                        },
                        new
                        {
                            NationalityId = 69,
                            IsActive = 1,
                            NationalityCode = "FK",
                            NationalityName = "FALKLAND ISLANDS new Nationality{ NationalityId=MALVINAS)"
                        },
                        new
                        {
                            NationalityId = 70,
                            IsActive = 1,
                            NationalityCode = "FO",
                            NationalityName = "FAROE ISLANDS"
                        },
                        new
                        {
                            NationalityId = 71,
                            IsActive = 1,
                            NationalityCode = "FJ",
                            NationalityName = "FIJI"
                        },
                        new
                        {
                            NationalityId = 72,
                            IsActive = 1,
                            NationalityCode = "FI",
                            NationalityName = "FINLAND"
                        },
                        new
                        {
                            NationalityId = 73,
                            IsActive = 1,
                            NationalityCode = "FR",
                            NationalityName = "FRANCE"
                        },
                        new
                        {
                            NationalityId = 74,
                            IsActive = 1,
                            NationalityCode = "GF",
                            NationalityName = "FRENCH GUIANA"
                        },
                        new
                        {
                            NationalityId = 75,
                            IsActive = 1,
                            NationalityCode = "PF",
                            NationalityName = "FRENCH POLYNESIA"
                        },
                        new
                        {
                            NationalityId = 76,
                            IsActive = 1,
                            NationalityCode = "TF",
                            NationalityName = "FRENCH SOUTHERN TERRITORIES"
                        },
                        new
                        {
                            NationalityId = 77,
                            IsActive = 1,
                            NationalityCode = "GA",
                            NationalityName = "GABON"
                        },
                        new
                        {
                            NationalityId = 78,
                            IsActive = 1,
                            NationalityCode = "GM",
                            NationalityName = "GAMBIA"
                        },
                        new
                        {
                            NationalityId = 79,
                            IsActive = 1,
                            NationalityCode = "GE",
                            NationalityName = "GEORGIA"
                        },
                        new
                        {
                            NationalityId = 80,
                            IsActive = 1,
                            NationalityCode = "DE",
                            NationalityName = "GERMANY"
                        },
                        new
                        {
                            NationalityId = 81,
                            IsActive = 1,
                            NationalityCode = "GH",
                            NationalityName = "GHANA"
                        },
                        new
                        {
                            NationalityId = 82,
                            IsActive = 1,
                            NationalityCode = "GI",
                            NationalityName = "GIBRALTAR"
                        },
                        new
                        {
                            NationalityId = 83,
                            IsActive = 1,
                            NationalityCode = "GR",
                            NationalityName = "GREECE"
                        },
                        new
                        {
                            NationalityId = 84,
                            IsActive = 1,
                            NationalityCode = "GL",
                            NationalityName = "GREENLAND"
                        },
                        new
                        {
                            NationalityId = 85,
                            IsActive = 1,
                            NationalityCode = "GD",
                            NationalityName = "GRENADA"
                        },
                        new
                        {
                            NationalityId = 86,
                            IsActive = 1,
                            NationalityCode = "GP",
                            NationalityName = "GUADELOUPE"
                        },
                        new
                        {
                            NationalityId = 87,
                            IsActive = 1,
                            NationalityCode = "GU",
                            NationalityName = "GUAM"
                        },
                        new
                        {
                            NationalityId = 88,
                            IsActive = 1,
                            NationalityCode = "GT",
                            NationalityName = "GUATEMALA"
                        },
                        new
                        {
                            NationalityId = 89,
                            IsActive = 1,
                            NationalityCode = "GN",
                            NationalityName = "GUINEA"
                        },
                        new
                        {
                            NationalityId = 90,
                            IsActive = 1,
                            NationalityCode = "GW",
                            NationalityName = "GUINEA-BISSAU"
                        },
                        new
                        {
                            NationalityId = 91,
                            IsActive = 1,
                            NationalityCode = "GY",
                            NationalityName = "GUYANA"
                        },
                        new
                        {
                            NationalityId = 92,
                            IsActive = 1,
                            NationalityCode = "HT",
                            NationalityName = "HAITI"
                        },
                        new
                        {
                            NationalityId = 93,
                            IsActive = 1,
                            NationalityCode = "HM",
                            NationalityName = "HEARD ISLAND AND MCDONALD ISLANDS"
                        },
                        new
                        {
                            NationalityId = 94,
                            IsActive = 1,
                            NationalityCode = "VA",
                            NationalityName = "HOLY SEE new Nationality{ NationalityId=VATICAN CITY STATE)"
                        },
                        new
                        {
                            NationalityId = 95,
                            IsActive = 1,
                            NationalityCode = "HN",
                            NationalityName = "HONDURAS"
                        },
                        new
                        {
                            NationalityId = 96,
                            IsActive = 1,
                            NationalityCode = "HK",
                            NationalityName = "HONG KONG"
                        },
                        new
                        {
                            NationalityId = 97,
                            IsActive = 1,
                            NationalityCode = "HU",
                            NationalityName = "HUNGARY"
                        },
                        new
                        {
                            NationalityId = 98,
                            IsActive = 1,
                            NationalityCode = "IS",
                            NationalityName = "ICELAND"
                        },
                        new
                        {
                            NationalityId = 99,
                            IsActive = 1,
                            NationalityCode = "IN",
                            NationalityName = "INDIA"
                        },
                        new
                        {
                            NationalityId = 100,
                            IsActive = 1,
                            NationalityCode = "ID",
                            NationalityName = "INDONESIA"
                        },
                        new
                        {
                            NationalityId = 101,
                            IsActive = 1,
                            NationalityCode = "IR",
                            NationalityName = "IRAN, ISLAMIC REPUBLIC OF"
                        },
                        new
                        {
                            NationalityId = 102,
                            IsActive = 1,
                            NationalityCode = "IQ",
                            NationalityName = "IRAQ"
                        },
                        new
                        {
                            NationalityId = 103,
                            IsActive = 1,
                            NationalityCode = "IE",
                            NationalityName = "IRELAND"
                        },
                        new
                        {
                            NationalityId = 104,
                            IsActive = 1,
                            NationalityCode = "IL",
                            NationalityName = "ISRAEL"
                        },
                        new
                        {
                            NationalityId = 105,
                            IsActive = 1,
                            NationalityCode = "IT",
                            NationalityName = "ITALY"
                        },
                        new
                        {
                            NationalityId = 106,
                            IsActive = 1,
                            NationalityCode = "JM",
                            NationalityName = "JAMAICA"
                        },
                        new
                        {
                            NationalityId = 107,
                            IsActive = 1,
                            NationalityCode = "JP",
                            NationalityName = "JAPAN"
                        },
                        new
                        {
                            NationalityId = 108,
                            IsActive = 1,
                            NationalityCode = "JO",
                            NationalityName = "JORDAN"
                        },
                        new
                        {
                            NationalityId = 109,
                            IsActive = 1,
                            NationalityCode = "KZ",
                            NationalityName = "KAZAKHSTAN"
                        },
                        new
                        {
                            NationalityId = 110,
                            IsActive = 1,
                            NationalityCode = "KE",
                            NationalityName = "KENYA"
                        },
                        new
                        {
                            NationalityId = 111,
                            IsActive = 1,
                            NationalityCode = "KI",
                            NationalityName = "KIRIBATI"
                        },
                        new
                        {
                            NationalityId = 112,
                            IsActive = 1,
                            NationalityCode = "KP",
                            NationalityName = "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"
                        },
                        new
                        {
                            NationalityId = 113,
                            IsActive = 1,
                            NationalityCode = "KR",
                            NationalityName = "KOREA, REPUBLIC OF"
                        },
                        new
                        {
                            NationalityId = 114,
                            IsActive = 1,
                            NationalityCode = "KW",
                            NationalityName = "KUWAIT"
                        },
                        new
                        {
                            NationalityId = 115,
                            IsActive = 1,
                            NationalityCode = "KG",
                            NationalityName = "KYRGYZSTAN"
                        },
                        new
                        {
                            NationalityId = 116,
                            IsActive = 1,
                            NationalityCode = "LA",
                            NationalityName = "LAO PEOPLE'S DEMOCRATIC REPUBLIC"
                        },
                        new
                        {
                            NationalityId = 117,
                            IsActive = 1,
                            NationalityCode = "LV",
                            NationalityName = "LATVIA"
                        },
                        new
                        {
                            NationalityId = 118,
                            IsActive = 1,
                            NationalityCode = "LB",
                            NationalityName = "LEBANON"
                        },
                        new
                        {
                            NationalityId = 119,
                            IsActive = 1,
                            NationalityCode = "LS",
                            NationalityName = "LESOTHO"
                        },
                        new
                        {
                            NationalityId = 120,
                            IsActive = 1,
                            NationalityCode = "LR",
                            NationalityName = "LIBERIA"
                        },
                        new
                        {
                            NationalityId = 121,
                            IsActive = 1,
                            NationalityCode = "LY",
                            NationalityName = "LIBYAN ARAB JAMAHIRIYA"
                        },
                        new
                        {
                            NationalityId = 122,
                            IsActive = 1,
                            NationalityCode = "LI",
                            NationalityName = "LIECHTENSTEIN"
                        },
                        new
                        {
                            NationalityId = 123,
                            IsActive = 1,
                            NationalityCode = "LT",
                            NationalityName = "LITHUANIA"
                        },
                        new
                        {
                            NationalityId = 124,
                            IsActive = 1,
                            NationalityCode = "LU",
                            NationalityName = "LUXEMBOURG"
                        },
                        new
                        {
                            NationalityId = 125,
                            IsActive = 1,
                            NationalityCode = "MO",
                            NationalityName = "MACAO"
                        },
                        new
                        {
                            NationalityId = 126,
                            IsActive = 1,
                            NationalityCode = "MK",
                            NationalityName = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"
                        },
                        new
                        {
                            NationalityId = 127,
                            IsActive = 1,
                            NationalityCode = "MG",
                            NationalityName = "MADAGASCAR"
                        },
                        new
                        {
                            NationalityId = 128,
                            IsActive = 1,
                            NationalityCode = "MW",
                            NationalityName = "MALAWI"
                        },
                        new
                        {
                            NationalityId = 129,
                            IsActive = 1,
                            NationalityCode = "MY",
                            NationalityName = "MALAYSIA"
                        },
                        new
                        {
                            NationalityId = 130,
                            IsActive = 1,
                            NationalityCode = "MV",
                            NationalityName = "MALDIVES"
                        },
                        new
                        {
                            NationalityId = 131,
                            IsActive = 1,
                            NationalityCode = "ML",
                            NationalityName = "MALI"
                        },
                        new
                        {
                            NationalityId = 132,
                            IsActive = 1,
                            NationalityCode = "MT",
                            NationalityName = "MALTA"
                        },
                        new
                        {
                            NationalityId = 133,
                            IsActive = 1,
                            NationalityCode = "MH",
                            NationalityName = "MARSHALL ISLANDS"
                        },
                        new
                        {
                            NationalityId = 134,
                            IsActive = 1,
                            NationalityCode = "MQ",
                            NationalityName = "MARTINIQUE"
                        },
                        new
                        {
                            NationalityId = 135,
                            IsActive = 1,
                            NationalityCode = "MR",
                            NationalityName = "MAURITANIA"
                        },
                        new
                        {
                            NationalityId = 136,
                            IsActive = 1,
                            NationalityCode = "MU",
                            NationalityName = "MAURITIUS"
                        },
                        new
                        {
                            NationalityId = 137,
                            IsActive = 1,
                            NationalityCode = "YT",
                            NationalityName = "MAYOTTE"
                        },
                        new
                        {
                            NationalityId = 138,
                            IsActive = 1,
                            NationalityCode = "MX",
                            NationalityName = "MEXICO"
                        },
                        new
                        {
                            NationalityId = 139,
                            IsActive = 1,
                            NationalityCode = "FM",
                            NationalityName = "MICRONESIA, FEDERATED STATES OF"
                        },
                        new
                        {
                            NationalityId = 140,
                            IsActive = 1,
                            NationalityCode = "MD",
                            NationalityName = "MOLDOVA, REPUBLIC OF"
                        },
                        new
                        {
                            NationalityId = 141,
                            IsActive = 1,
                            NationalityCode = "MC",
                            NationalityName = "MONACO"
                        },
                        new
                        {
                            NationalityId = 142,
                            IsActive = 1,
                            NationalityCode = "MN",
                            NationalityName = "MONGOLIA"
                        },
                        new
                        {
                            NationalityId = 143,
                            IsActive = 1,
                            NationalityCode = "MS",
                            NationalityName = "MONTSERRAT"
                        },
                        new
                        {
                            NationalityId = 144,
                            IsActive = 1,
                            NationalityCode = "MA",
                            NationalityName = "MOROCCO"
                        },
                        new
                        {
                            NationalityId = 145,
                            IsActive = 1,
                            NationalityCode = "MZ",
                            NationalityName = "MOZAMBIQUE"
                        },
                        new
                        {
                            NationalityId = 146,
                            IsActive = 1,
                            NationalityCode = "MM",
                            NationalityName = "MYANMAR"
                        },
                        new
                        {
                            NationalityId = 147,
                            IsActive = 1,
                            NationalityCode = "NA",
                            NationalityName = "NAMIBIA"
                        },
                        new
                        {
                            NationalityId = 148,
                            IsActive = 1,
                            NationalityCode = "NR",
                            NationalityName = "NAURU"
                        },
                        new
                        {
                            NationalityId = 149,
                            IsActive = 1,
                            NationalityCode = "NP",
                            NationalityName = "NEPAL"
                        },
                        new
                        {
                            NationalityId = 150,
                            IsActive = 1,
                            NationalityCode = "NL",
                            NationalityName = "NETHERLANDS"
                        },
                        new
                        {
                            NationalityId = 151,
                            IsActive = 1,
                            NationalityCode = "AN",
                            NationalityName = "NETHERLANDS ANTILLES"
                        },
                        new
                        {
                            NationalityId = 152,
                            IsActive = 1,
                            NationalityCode = "NC",
                            NationalityName = "NEW CALEDONIA"
                        },
                        new
                        {
                            NationalityId = 153,
                            IsActive = 1,
                            NationalityCode = "NZ",
                            NationalityName = "NEW ZEALAND"
                        },
                        new
                        {
                            NationalityId = 154,
                            IsActive = 1,
                            NationalityCode = "NI",
                            NationalityName = "NICARAGUA"
                        },
                        new
                        {
                            NationalityId = 155,
                            IsActive = 1,
                            NationalityCode = "NE",
                            NationalityName = "NIGER"
                        },
                        new
                        {
                            NationalityId = 156,
                            IsActive = 1,
                            NationalityCode = "NG",
                            NationalityName = "NIGERIA"
                        },
                        new
                        {
                            NationalityId = 157,
                            IsActive = 1,
                            NationalityCode = "NU",
                            NationalityName = "NIUE"
                        },
                        new
                        {
                            NationalityId = 158,
                            IsActive = 1,
                            NationalityCode = "NF",
                            NationalityName = "NORFOLK ISLAND"
                        },
                        new
                        {
                            NationalityId = 159,
                            IsActive = 1,
                            NationalityCode = "MP",
                            NationalityName = "NORTHERN MARIANA ISLANDS"
                        },
                        new
                        {
                            NationalityId = 160,
                            IsActive = 1,
                            NationalityCode = "NO",
                            NationalityName = "NORWAY"
                        },
                        new
                        {
                            NationalityId = 161,
                            IsActive = 1,
                            NationalityCode = "OM",
                            NationalityName = "OMAN"
                        },
                        new
                        {
                            NationalityId = 162,
                            IsActive = 1,
                            NationalityCode = "PK",
                            NationalityName = "PAKISTAN"
                        },
                        new
                        {
                            NationalityId = 163,
                            IsActive = 1,
                            NationalityCode = "PW",
                            NationalityName = "PALAU"
                        },
                        new
                        {
                            NationalityId = 164,
                            IsActive = 1,
                            NationalityCode = "PS",
                            NationalityName = "PALESTINIAN TERRITORY, OCCUPIED"
                        },
                        new
                        {
                            NationalityId = 165,
                            IsActive = 1,
                            NationalityCode = "PA",
                            NationalityName = "PANAMA"
                        },
                        new
                        {
                            NationalityId = 166,
                            IsActive = 1,
                            NationalityCode = "PG",
                            NationalityName = "PAPUA NEW GUINEA"
                        },
                        new
                        {
                            NationalityId = 167,
                            IsActive = 1,
                            NationalityCode = "PY",
                            NationalityName = "PARAGUAY"
                        },
                        new
                        {
                            NationalityId = 168,
                            IsActive = 1,
                            NationalityCode = "PE",
                            NationalityName = "PERU"
                        },
                        new
                        {
                            NationalityId = 169,
                            IsActive = 1,
                            NationalityCode = "PH",
                            NationalityName = "PHILIPPINES"
                        },
                        new
                        {
                            NationalityId = 170,
                            IsActive = 1,
                            NationalityCode = "PN",
                            NationalityName = "PITCAIRN"
                        },
                        new
                        {
                            NationalityId = 171,
                            IsActive = 1,
                            NationalityCode = "PL",
                            NationalityName = "POLAND"
                        },
                        new
                        {
                            NationalityId = 172,
                            IsActive = 1,
                            NationalityCode = "PT",
                            NationalityName = "PORTUGAL"
                        },
                        new
                        {
                            NationalityId = 173,
                            IsActive = 1,
                            NationalityCode = "PR",
                            NationalityName = "PUERTO RICO"
                        },
                        new
                        {
                            NationalityId = 174,
                            IsActive = 1,
                            NationalityCode = "QA",
                            NationalityName = "QATAR"
                        },
                        new
                        {
                            NationalityId = 175,
                            IsActive = 1,
                            NationalityCode = "RE",
                            NationalityName = "REUNION"
                        },
                        new
                        {
                            NationalityId = 176,
                            IsActive = 1,
                            NationalityCode = "RO",
                            NationalityName = "ROMANIA"
                        },
                        new
                        {
                            NationalityId = 177,
                            IsActive = 1,
                            NationalityCode = "RU",
                            NationalityName = "RUSSIAN FEDERATION"
                        },
                        new
                        {
                            NationalityId = 178,
                            IsActive = 1,
                            NationalityCode = "RW",
                            NationalityName = "RWANDA"
                        },
                        new
                        {
                            NationalityId = 179,
                            IsActive = 1,
                            NationalityCode = "SH",
                            NationalityName = "SAINT HELENA"
                        },
                        new
                        {
                            NationalityId = 180,
                            IsActive = 1,
                            NationalityCode = "KN",
                            NationalityName = "SAINT KITTS AND NEVIS"
                        },
                        new
                        {
                            NationalityId = 181,
                            IsActive = 1,
                            NationalityCode = "LC",
                            NationalityName = "SAINT LUCIA"
                        },
                        new
                        {
                            NationalityId = 182,
                            IsActive = 1,
                            NationalityCode = "PM",
                            NationalityName = "SAINT PIERRE AND MIQUELON"
                        },
                        new
                        {
                            NationalityId = 183,
                            IsActive = 1,
                            NationalityCode = "VC",
                            NationalityName = "SAINT VINCENT AND THE GRENADINES"
                        },
                        new
                        {
                            NationalityId = 184,
                            IsActive = 1,
                            NationalityCode = "WS",
                            NationalityName = "SAMOA"
                        },
                        new
                        {
                            NationalityId = 185,
                            IsActive = 1,
                            NationalityCode = "SM",
                            NationalityName = "SAN MARINO"
                        },
                        new
                        {
                            NationalityId = 186,
                            IsActive = 1,
                            NationalityCode = "ST",
                            NationalityName = "SAO TOME AND PRINCIPE"
                        },
                        new
                        {
                            NationalityId = 187,
                            IsActive = 1,
                            NationalityCode = "SA",
                            NationalityName = "SAUDI ARABIA"
                        },
                        new
                        {
                            NationalityId = 188,
                            IsActive = 1,
                            NationalityCode = "SN",
                            NationalityName = "SENEGAL"
                        },
                        new
                        {
                            NationalityId = 189,
                            IsActive = 1,
                            NationalityCode = "CS",
                            NationalityName = "SERBIA AND MONTENEGRO"
                        },
                        new
                        {
                            NationalityId = 190,
                            IsActive = 1,
                            NationalityCode = "SC",
                            NationalityName = "SEYCHELLES"
                        },
                        new
                        {
                            NationalityId = 191,
                            IsActive = 1,
                            NationalityCode = "SL",
                            NationalityName = "SIERRA LEONE"
                        },
                        new
                        {
                            NationalityId = 192,
                            IsActive = 1,
                            NationalityCode = "SG",
                            NationalityName = "SINGAPORE"
                        },
                        new
                        {
                            NationalityId = 193,
                            IsActive = 1,
                            NationalityCode = "SK",
                            NationalityName = "SLOVAKIA"
                        },
                        new
                        {
                            NationalityId = 194,
                            IsActive = 1,
                            NationalityCode = "SI",
                            NationalityName = "SLOVENIA"
                        },
                        new
                        {
                            NationalityId = 195,
                            IsActive = 1,
                            NationalityCode = "SB",
                            NationalityName = "SOLOMON ISLANDS"
                        },
                        new
                        {
                            NationalityId = 196,
                            IsActive = 1,
                            NationalityCode = "SO",
                            NationalityName = "SOMALIA"
                        },
                        new
                        {
                            NationalityId = 197,
                            IsActive = 1,
                            NationalityCode = "ZA",
                            NationalityName = "SOUTH AFRICA"
                        },
                        new
                        {
                            NationalityId = 198,
                            IsActive = 1,
                            NationalityCode = "GS",
                            NationalityName = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"
                        },
                        new
                        {
                            NationalityId = 199,
                            IsActive = 1,
                            NationalityCode = "ES",
                            NationalityName = "SPAIN"
                        },
                        new
                        {
                            NationalityId = 200,
                            IsActive = 1,
                            NationalityCode = "LK",
                            NationalityName = "SRI LANKA"
                        },
                        new
                        {
                            NationalityId = 201,
                            IsActive = 1,
                            NationalityCode = "SD",
                            NationalityName = "SUDAN"
                        },
                        new
                        {
                            NationalityId = 202,
                            IsActive = 1,
                            NationalityCode = "SR",
                            NationalityName = "SURINAME"
                        },
                        new
                        {
                            NationalityId = 203,
                            IsActive = 1,
                            NationalityCode = "SJ",
                            NationalityName = "SVALBARD AND JAN MAYEN"
                        },
                        new
                        {
                            NationalityId = 204,
                            IsActive = 1,
                            NationalityCode = "SZ",
                            NationalityName = "SWAZILAND"
                        },
                        new
                        {
                            NationalityId = 205,
                            IsActive = 1,
                            NationalityCode = "SE",
                            NationalityName = "SWEDEN"
                        },
                        new
                        {
                            NationalityId = 206,
                            IsActive = 1,
                            NationalityCode = "CH",
                            NationalityName = "SWITZERLAND"
                        },
                        new
                        {
                            NationalityId = 207,
                            IsActive = 1,
                            NationalityCode = "SY",
                            NationalityName = "SYRIAN ARAB REPUBLIC"
                        },
                        new
                        {
                            NationalityId = 208,
                            IsActive = 1,
                            NationalityCode = "TW",
                            NationalityName = "TAIWAN, PROVINCE OF CHINA"
                        },
                        new
                        {
                            NationalityId = 209,
                            IsActive = 1,
                            NationalityCode = "TJ",
                            NationalityName = "TAJIKISTAN"
                        },
                        new
                        {
                            NationalityId = 210,
                            IsActive = 1,
                            NationalityCode = "TZ",
                            NationalityName = "TANZANIA, UNITED REPUBLIC OF"
                        },
                        new
                        {
                            NationalityId = 211,
                            IsActive = 1,
                            NationalityCode = "TH",
                            NationalityName = "THAILAND"
                        },
                        new
                        {
                            NationalityId = 212,
                            IsActive = 1,
                            NationalityCode = "TL",
                            NationalityName = "TIMOR-LESTE"
                        },
                        new
                        {
                            NationalityId = 213,
                            IsActive = 1,
                            NationalityCode = "TG",
                            NationalityName = "TOGO"
                        },
                        new
                        {
                            NationalityId = 214,
                            IsActive = 1,
                            NationalityCode = "TK",
                            NationalityName = "TOKELAU"
                        },
                        new
                        {
                            NationalityId = 215,
                            IsActive = 1,
                            NationalityCode = "TO",
                            NationalityName = "TONGA"
                        },
                        new
                        {
                            NationalityId = 216,
                            IsActive = 1,
                            NationalityCode = "TT",
                            NationalityName = "TRINIDAD AND TOBAGO"
                        },
                        new
                        {
                            NationalityId = 217,
                            IsActive = 1,
                            NationalityCode = "TN",
                            NationalityName = "TUNISIA"
                        },
                        new
                        {
                            NationalityId = 218,
                            IsActive = 1,
                            NationalityCode = "TR",
                            NationalityName = "TURKEY"
                        },
                        new
                        {
                            NationalityId = 219,
                            IsActive = 1,
                            NationalityCode = "TM",
                            NationalityName = "TURKMENISTAN"
                        },
                        new
                        {
                            NationalityId = 220,
                            IsActive = 1,
                            NationalityCode = "TC",
                            NationalityName = "TURKS AND CAICOS ISLANDS"
                        },
                        new
                        {
                            NationalityId = 221,
                            IsActive = 1,
                            NationalityCode = "TV",
                            NationalityName = "TUVALU"
                        },
                        new
                        {
                            NationalityId = 222,
                            IsActive = 1,
                            NationalityCode = "UG",
                            NationalityName = "UGANDA"
                        },
                        new
                        {
                            NationalityId = 223,
                            IsActive = 1,
                            NationalityCode = "UA",
                            NationalityName = "UKRAINE"
                        },
                        new
                        {
                            NationalityId = 224,
                            IsActive = 1,
                            NationalityCode = "AE",
                            NationalityName = "UNITED ARAB EMIRATES"
                        },
                        new
                        {
                            NationalityId = 225,
                            IsActive = 1,
                            NationalityCode = "GB",
                            NationalityName = "UNITED KINGDOM"
                        },
                        new
                        {
                            NationalityId = 226,
                            IsActive = 1,
                            NationalityCode = "US",
                            NationalityName = "UNITED STATES"
                        },
                        new
                        {
                            NationalityId = 227,
                            IsActive = 1,
                            NationalityCode = "UM",
                            NationalityName = "UNITED STATES MINOR OUTLYING ISLANDS"
                        },
                        new
                        {
                            NationalityId = 228,
                            IsActive = 1,
                            NationalityCode = "UY",
                            NationalityName = "URUGUAY"
                        },
                        new
                        {
                            NationalityId = 229,
                            IsActive = 1,
                            NationalityCode = "UZ",
                            NationalityName = "UZBEKISTAN"
                        },
                        new
                        {
                            NationalityId = 230,
                            IsActive = 1,
                            NationalityCode = "VU",
                            NationalityName = "VANUATU"
                        },
                        new
                        {
                            NationalityId = 231,
                            IsActive = 1,
                            NationalityCode = "VE",
                            NationalityName = "VENEZUELA"
                        },
                        new
                        {
                            NationalityId = 232,
                            IsActive = 1,
                            NationalityCode = "VN",
                            NationalityName = "VIET NAM"
                        },
                        new
                        {
                            NationalityId = 233,
                            IsActive = 1,
                            NationalityCode = "VG",
                            NationalityName = "VIRGIN ISLANDS, BRITISH"
                        },
                        new
                        {
                            NationalityId = 234,
                            IsActive = 1,
                            NationalityCode = "VI",
                            NationalityName = "VIRGIN ISLANDS, U.S."
                        },
                        new
                        {
                            NationalityId = 235,
                            IsActive = 1,
                            NationalityCode = "WF",
                            NationalityName = "WALLIS AND FUTUNA"
                        },
                        new
                        {
                            NationalityId = 236,
                            IsActive = 1,
                            NationalityCode = "EH",
                            NationalityName = "WESTERN SAHARA"
                        },
                        new
                        {
                            NationalityId = 237,
                            IsActive = 1,
                            NationalityCode = "YE",
                            NationalityName = "YEMEN"
                        },
                        new
                        {
                            NationalityId = 238,
                            IsActive = 1,
                            NationalityCode = "ZM",
                            NationalityName = "ZAMBIA"
                        },
                        new
                        {
                            NationalityId = 239,
                            IsActive = 1,
                            NationalityCode = "ZW",
                            NationalityName = "ZIMBABWE"
                        });
                });

            modelBuilder.Entity("dentalclinic.Common.Model.Domain.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeId"), 1L, 1);

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeId = 1,
                            UserTypeName = "Doctor"
                        },
                        new
                        {
                            UserTypeId = 2,
                            UserTypeName = "Nurse"
                        },
                        new
                        {
                            UserTypeId = 3,
                            UserTypeName = "Reception"
                        },
                        new
                        {
                            UserTypeId = 4,
                            UserTypeName = "Admin"
                        },
                        new
                        {
                            UserTypeId = 5,
                            UserTypeName = "Other"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("dentalclinic.Common.Model.Domain.ApplicationUser", b =>
                {
                    b.HasOne("dentalclinic.Common.Model.Domain.Nationality", "Nationality")
                        .WithMany("ApplicationUser")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dentalclinic.Common.Model.Domain.UserType", "UserType")
                        .WithMany("ApplicationUser")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nationality");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("dentalclinic.Common.Model.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("dentalclinic.Common.Model.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dentalclinic.Common.Model.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("dentalclinic.Common.Model.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dentalclinic.Common.Model.Domain.Nationality", b =>
                {
                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("dentalclinic.Common.Model.Domain.UserType", b =>
                {
                    b.Navigation("ApplicationUser");
                });
#pragma warning restore 612, 618
        }
    }
}
