using dentalclinic.Common.Model.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
namespace dentalclinic.Domain.SeedData
{
    public static class SeedDataModelBuilderExtenstion
    {
        public static void Seed(this ModelBuilder builder)
        {
          
            //builder.Entity<IdentityRole>().HasData(
            //    new IdentityRole { Name = "Admin" },
            //    new IdentityRole { Name = "Doctor" },
            //    new IdentityRole { Name = "Reception" }
            //);

            builder.Entity<UserType>().HasData(
               new UserType { UserTypeId=1,UserTypeName = "Doctor" },
               new UserType { UserTypeId = 2, UserTypeName = "Nurse" },
               new UserType { UserTypeId = 3, UserTypeName = "Reception" },
               new UserType { UserTypeId = 4, UserTypeName = "Admin" },
               new UserType { UserTypeId = 5, UserTypeName = "Other" }
           );

            builder.Entity<Nationality>().HasData(
                 new Nationality { NationalityId = 1, NationalityCode = "AF" , NationalityName = "AFGHANISTAN", IsActive = 1 },
                 new Nationality { NationalityId = 2, NationalityCode = "AL" , NationalityName = "ALBANIA", IsActive = 1 },
                 new Nationality { NationalityId = 3, NationalityCode = "DZ" , NationalityName = "ALGERIA", IsActive = 1 },
                 new Nationality { NationalityId = 4, NationalityCode = "AS" , NationalityName = "AMERICAN SAMOA", IsActive = 1 },
                 new Nationality { NationalityId = 5, NationalityCode = "AD" , NationalityName = "ANDORRA", IsActive = 1 },
                 new Nationality { NationalityId = 6, NationalityCode = "AO" , NationalityName = "ANGOLA", IsActive = 1 },
                 new Nationality { NationalityId = 7, NationalityCode = "AI" , NationalityName = "ANGUILLA", IsActive = 1 },
                 new Nationality { NationalityId = 8, NationalityCode = "AQ" , NationalityName = "ANTARCTICA", IsActive = 1 },
                 new Nationality { NationalityId = 9, NationalityCode = "AG",  NationalityName = "ANTIGUA AND BARBUDA", IsActive = 1 },
                 new Nationality { NationalityId = 10, NationalityCode = "AR" , NationalityName = "ARGENTINA", IsActive = 1 },
                 new Nationality { NationalityId = 11, NationalityCode = "AM" , NationalityName = "ARMENIA", IsActive = 1 },
                 new Nationality { NationalityId = 12, NationalityCode = "AW" , NationalityName = "ARUBA", IsActive = 1 },
                 new Nationality { NationalityId = 13, NationalityCode = "AU" , NationalityName = "AUSTRALIA", IsActive = 1 },
                 new Nationality { NationalityId = 14, NationalityCode = "AT" , NationalityName = "AUSTRIA", IsActive = 1 },
                 new Nationality { NationalityId = 15, NationalityCode = "AZ" , NationalityName = "AZERBAIJAN", IsActive = 1 },
                 new Nationality { NationalityId = 16, NationalityCode = "BS" , NationalityName = "BAHAMAS", IsActive = 1 },
                 new Nationality { NationalityId = 17, NationalityCode = "BH" , NationalityName = "BAHRAIN", IsActive = 1 },
                 new Nationality { NationalityId = 18, NationalityCode = "BD" , NationalityName = "BANGLADESH", IsActive = 1 },
                 new Nationality { NationalityId = 19, NationalityCode = "BB" , NationalityName = "BARBADOS", IsActive = 1 },
                 new Nationality { NationalityId = 20, NationalityCode = "BY" , NationalityName = "BELARUS", IsActive = 1 },
                 new Nationality { NationalityId = 21, NationalityCode = "BE" , NationalityName = "BELGIUM", IsActive = 1 },
                 new Nationality { NationalityId = 22, NationalityCode = "BZ" , NationalityName = "BELIZE", IsActive = 1 },
                 new Nationality { NationalityId = 23, NationalityCode = "BJ" , NationalityName = "BENIN", IsActive = 1 },
                 new Nationality { NationalityId = 24, NationalityCode = "BM" , NationalityName = "BERMUDA", IsActive = 1 },
                 new Nationality { NationalityId = 25, NationalityCode = "BT" , NationalityName = "BHUTAN", IsActive = 1 },
                 new Nationality { NationalityId = 26, NationalityCode = "BO" , NationalityName = "BOLIVIA", IsActive = 1 },
                 new Nationality { NationalityId = 27, NationalityCode = "BA" , NationalityName = "BOSNIA AND HERZEGOVINA", IsActive = 1 },
                 new Nationality { NationalityId = 28, NationalityCode = "BW" , NationalityName = "BOTSWANA", IsActive = 1 },
                 new Nationality { NationalityId = 29, NationalityCode = "BV" , NationalityName = "BOUVET ISLAND", IsActive = 1 },
                 new Nationality { NationalityId = 30, NationalityCode = "BR" , NationalityName = "BRAZIL", IsActive = 1 },
                 new Nationality { NationalityId = 31, NationalityCode = "IO" , NationalityName = "BRITISH INDIAN OCEAN TERRITORY", IsActive = 1 },
                 new Nationality { NationalityId = 32, NationalityCode = "BN" , NationalityName = "BRUNEI DARUSSALAM", IsActive = 1 },
                 new Nationality { NationalityId = 33, NationalityCode = "BG" , NationalityName = "BULGARIA", IsActive = 1 },
                 new Nationality { NationalityId = 34, NationalityCode = "BF" , NationalityName = "BURKINA FASO", IsActive = 1 },
                 new Nationality { NationalityId = 35, NationalityCode = "BI" , NationalityName = "BURUNDI", IsActive = 1 },
                 new Nationality { NationalityId = 36, NationalityCode = "KH" , NationalityName = "CAMBODIA", IsActive = 1 },
                 new Nationality { NationalityId = 37, NationalityCode = "CM" , NationalityName = "CAMEROON", IsActive = 1 },
                 new Nationality { NationalityId = 38, NationalityCode = "CA" , NationalityName = "CANADA", IsActive = 1 },
                 new Nationality { NationalityId = 39, NationalityCode = "CV" , NationalityName = "CAPE VERDE", IsActive = 1 },
                 new Nationality { NationalityId = 40, NationalityCode = "KY" , NationalityName = "CAYMAN ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 41, NationalityCode = "CF" , NationalityName = "CENTRAL AFRICAN REPUBLIC", IsActive = 1 },
                 new Nationality { NationalityId = 42, NationalityCode = "TD" , NationalityName = "CHAD", IsActive = 1 },
                 new Nationality { NationalityId = 43, NationalityCode = "CL" , NationalityName = "CHILE", IsActive = 1 },
                 new Nationality { NationalityId = 44, NationalityCode = "CN" , NationalityName = "CHINA", IsActive = 1 },
                 new Nationality { NationalityId = 45, NationalityCode = "CX" , NationalityName = "CHRISTMAS ISLAND", IsActive = 1 },
                 new Nationality { NationalityId = 46, NationalityCode = "CC" , NationalityName = "COCOS new Nationality{ NationalityId=KEELING) ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 47, NationalityCode = "CO" , NationalityName = "COLOMBIA", IsActive = 1 },
                 new Nationality { NationalityId = 48, NationalityCode = "KM" , NationalityName = "COMOROS", IsActive = 1 },
                 new Nationality { NationalityId = 49, NationalityCode = "CG" , NationalityName = "CONGO", IsActive = 1 },
                 new Nationality { NationalityId = 50, NationalityCode = "CD" , NationalityName = "CONGO, THE DEMOCRATIC REPUBLIC OF THE", IsActive = 1 },
                 new Nationality { NationalityId = 51, NationalityCode = "CK" , NationalityName = "COOK ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 52, NationalityCode = "CR" , NationalityName = "COSTA RICA", IsActive = 1 },
                 new Nationality { NationalityId = 53, NationalityCode = "CI" , NationalityName = "COTE D'IVOIRE", IsActive = 1 },
                 new Nationality { NationalityId = 54, NationalityCode = "HR" , NationalityName = "CROATIA", IsActive = 1 },
                 new Nationality { NationalityId = 55, NationalityCode = "CU" , NationalityName = "CUBA", IsActive = 1 },
                 new Nationality { NationalityId = 56, NationalityCode = "CY" , NationalityName = "CYPRUS", IsActive = 1 },
                 new Nationality { NationalityId = 57, NationalityCode = "CZ" , NationalityName = "CZECH REPUBLIC", IsActive = 1 },
                 new Nationality { NationalityId = 58, NationalityCode = "DK" , NationalityName = "DENMARK", IsActive = 1 },
                 new Nationality { NationalityId = 59, NationalityCode = "DJ" , NationalityName = "DJIBOUTI", IsActive = 1 },
                 new Nationality { NationalityId = 60, NationalityCode = "DM" , NationalityName = "DOMINICA", IsActive = 1 },
                 new Nationality { NationalityId = 61, NationalityCode = "DO" , NationalityName = "DOMINICAN REPUBLIC", IsActive = 1 },
                 new Nationality { NationalityId = 62, NationalityCode = "EC" , NationalityName = "ECUADOR", IsActive = 1 },
                 new Nationality { NationalityId = 63, NationalityCode = "EG" , NationalityName = "EGYPT", IsActive = 1 },
                 new Nationality { NationalityId = 64, NationalityCode = "SV" , NationalityName = "EL SALVADOR", IsActive = 1 },
                 new Nationality { NationalityId = 65, NationalityCode = "GQ" , NationalityName = "EQUATORIAL GUINEA", IsActive = 1 },
                 new Nationality { NationalityId = 66, NationalityCode = "ER" , NationalityName = "ERITREA", IsActive = 1 },
                 new Nationality { NationalityId = 67, NationalityCode = "EE" , NationalityName = "ESTONIA", IsActive = 1 },
                 new Nationality { NationalityId = 68, NationalityCode = "ET" , NationalityName = "ETHIOPIA", IsActive = 1 },
                 new Nationality { NationalityId = 69, NationalityCode = "FK" , NationalityName = "FALKLAND ISLANDS new Nationality{ NationalityId=MALVINAS)", IsActive = 1 },
                 new Nationality { NationalityId = 70, NationalityCode = "FO" , NationalityName = "FAROE ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 71, NationalityCode = "FJ" , NationalityName = "FIJI", IsActive = 1 },
                 new Nationality { NationalityId = 72, NationalityCode = "FI" , NationalityName = "FINLAND", IsActive = 1 },
                 new Nationality { NationalityId = 73, NationalityCode = "FR" , NationalityName = "FRANCE", IsActive = 1 },
                 new Nationality { NationalityId = 74, NationalityCode = "GF" , NationalityName = "FRENCH GUIANA", IsActive = 1 },
                 new Nationality { NationalityId = 75, NationalityCode = "PF" , NationalityName = "FRENCH POLYNESIA", IsActive = 1 },
                 new Nationality { NationalityId = 76, NationalityCode = "TF" , NationalityName = "FRENCH SOUTHERN TERRITORIES", IsActive = 1 },
                 new Nationality { NationalityId = 77, NationalityCode = "GA" , NationalityName = "GABON", IsActive = 1 },
                 new Nationality { NationalityId = 78, NationalityCode = "GM" , NationalityName = "GAMBIA", IsActive = 1 },
                 new Nationality { NationalityId = 79, NationalityCode = "GE" , NationalityName = "GEORGIA", IsActive = 1 },
                 new Nationality { NationalityId = 80, NationalityCode = "DE" , NationalityName = "GERMANY", IsActive = 1 },
                 new Nationality { NationalityId = 81, NationalityCode = "GH" , NationalityName = "GHANA", IsActive = 1 },
                 new Nationality { NationalityId = 82, NationalityCode = "GI" , NationalityName = "GIBRALTAR", IsActive = 1 },
                 new Nationality { NationalityId = 83, NationalityCode = "GR" , NationalityName = "GREECE", IsActive = 1 },
                 new Nationality { NationalityId = 84, NationalityCode = "GL" , NationalityName = "GREENLAND", IsActive = 1 },
                 new Nationality { NationalityId = 85, NationalityCode = "GD" , NationalityName = "GRENADA", IsActive = 1 },
                 new Nationality { NationalityId = 86, NationalityCode = "GP" , NationalityName = "GUADELOUPE", IsActive = 1 },
                 new Nationality { NationalityId = 87, NationalityCode = "GU" , NationalityName = "GUAM", IsActive = 1 },
                 new Nationality { NationalityId = 88, NationalityCode = "GT" , NationalityName = "GUATEMALA", IsActive = 1 },
                 new Nationality { NationalityId = 89, NationalityCode = "GN" , NationalityName = "GUINEA", IsActive = 1 },
                 new Nationality { NationalityId = 90, NationalityCode = "GW" , NationalityName = "GUINEA-BISSAU", IsActive = 1 },
                 new Nationality { NationalityId = 91, NationalityCode = "GY" , NationalityName = "GUYANA", IsActive = 1 },
                 new Nationality { NationalityId = 92, NationalityCode = "HT" , NationalityName = "HAITI", IsActive = 1 },
                 new Nationality { NationalityId = 93, NationalityCode = "HM" , NationalityName = "HEARD ISLAND AND MCDONALD ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 94, NationalityCode = "VA" , NationalityName = "HOLY SEE new Nationality{ NationalityId=VATICAN CITY STATE)", IsActive = 1 },
                 new Nationality { NationalityId = 95, NationalityCode = "HN" , NationalityName = "HONDURAS", IsActive = 1 },
                 new Nationality { NationalityId = 96, NationalityCode = "HK" , NationalityName = "HONG KONG", IsActive = 1 },
                 new Nationality { NationalityId = 97, NationalityCode = "HU" , NationalityName = "HUNGARY", IsActive = 1 },
                 new Nationality { NationalityId = 98, NationalityCode = "IS" , NationalityName = "ICELAND", IsActive = 1 },
                 new Nationality { NationalityId = 99, NationalityCode = "IN" , NationalityName = "INDIA", IsActive = 1 },
                 new Nationality { NationalityId = 100, NationalityCode = "ID" , NationalityName = "INDONESIA", IsActive = 1 },
                 new Nationality { NationalityId = 101, NationalityCode = "IR" , NationalityName = "IRAN, ISLAMIC REPUBLIC OF", IsActive = 1 },
                 new Nationality { NationalityId = 102, NationalityCode = "IQ" , NationalityName = "IRAQ", IsActive = 1 },
                 new Nationality { NationalityId = 103, NationalityCode = "IE" , NationalityName = "IRELAND", IsActive = 1 },
                 new Nationality { NationalityId = 104, NationalityCode = "IL" , NationalityName = "ISRAEL", IsActive = 1 },
                 new Nationality { NationalityId = 105, NationalityCode = "IT" , NationalityName = "ITALY", IsActive = 1 },
                 new Nationality { NationalityId = 106, NationalityCode = "JM" , NationalityName = "JAMAICA", IsActive = 1 },
                 new Nationality { NationalityId = 107, NationalityCode = "JP" , NationalityName = "JAPAN", IsActive = 1 },
                 new Nationality { NationalityId = 108, NationalityCode = "JO" , NationalityName = "JORDAN", IsActive = 1 },
                 new Nationality { NationalityId = 109, NationalityCode = "KZ" , NationalityName = "KAZAKHSTAN", IsActive = 1 },
                 new Nationality { NationalityId = 110, NationalityCode = "KE" , NationalityName = "KENYA", IsActive = 1 },
                 new Nationality { NationalityId = 111, NationalityCode = "KI" , NationalityName = "KIRIBATI", IsActive = 1 },
                 new Nationality { NationalityId = 112, NationalityCode = "KP" , NationalityName = "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", IsActive = 1 },
                 new Nationality { NationalityId = 113, NationalityCode = "KR" , NationalityName = "KOREA, REPUBLIC OF", IsActive = 1 },
                 new Nationality { NationalityId = 114, NationalityCode = "KW" , NationalityName = "KUWAIT", IsActive = 1 },
                 new Nationality { NationalityId = 115, NationalityCode = "KG" , NationalityName = "KYRGYZSTAN", IsActive = 1 },
                 new Nationality { NationalityId = 116, NationalityCode = "LA" , NationalityName = "LAO PEOPLE'S DEMOCRATIC REPUBLIC", IsActive = 1 },
                 new Nationality { NationalityId = 117, NationalityCode = "LV" , NationalityName = "LATVIA", IsActive = 1 },
                 new Nationality { NationalityId = 118, NationalityCode = "LB" , NationalityName = "LEBANON", IsActive = 1 },
                 new Nationality { NationalityId = 119, NationalityCode = "LS" , NationalityName = "LESOTHO", IsActive = 1 },
                 new Nationality { NationalityId = 120, NationalityCode = "LR" , NationalityName = "LIBERIA", IsActive = 1 },
                 new Nationality { NationalityId = 121, NationalityCode = "LY" , NationalityName = "LIBYAN ARAB JAMAHIRIYA", IsActive = 1 },
                 new Nationality { NationalityId = 122, NationalityCode = "LI" , NationalityName = "LIECHTENSTEIN", IsActive = 1 },
                 new Nationality { NationalityId = 123, NationalityCode = "LT" , NationalityName = "LITHUANIA", IsActive = 1 },
                 new Nationality { NationalityId = 124, NationalityCode = "LU" , NationalityName = "LUXEMBOURG", IsActive = 1 },
                 new Nationality { NationalityId = 125, NationalityCode = "MO" , NationalityName = "MACAO", IsActive = 1 },
                 new Nationality { NationalityId = 126, NationalityCode = "MK" , NationalityName = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", IsActive = 1 },
                 new Nationality { NationalityId = 127, NationalityCode = "MG" , NationalityName = "MADAGASCAR", IsActive = 1 },
                 new Nationality { NationalityId = 128, NationalityCode = "MW" , NationalityName = "MALAWI", IsActive = 1 },
                 new Nationality { NationalityId = 129, NationalityCode = "MY" , NationalityName = "MALAYSIA", IsActive = 1 },
                 new Nationality { NationalityId = 130, NationalityCode = "MV" , NationalityName = "MALDIVES", IsActive = 1 },
                 new Nationality { NationalityId = 131, NationalityCode = "ML" , NationalityName = "MALI", IsActive = 1 },
                 new Nationality { NationalityId = 132, NationalityCode = "MT" , NationalityName = "MALTA", IsActive = 1 },
                 new Nationality { NationalityId = 133, NationalityCode = "MH" , NationalityName = "MARSHALL ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 134, NationalityCode = "MQ" , NationalityName = "MARTINIQUE", IsActive = 1 },
                 new Nationality { NationalityId = 135, NationalityCode = "MR" , NationalityName = "MAURITANIA", IsActive = 1 },
                 new Nationality { NationalityId = 136, NationalityCode = "MU" , NationalityName = "MAURITIUS", IsActive = 1 },
                 new Nationality { NationalityId = 137, NationalityCode = "YT" , NationalityName = "MAYOTTE", IsActive = 1 },
                 new Nationality { NationalityId = 138, NationalityCode = "MX" , NationalityName = "MEXICO", IsActive = 1 },
                 new Nationality { NationalityId = 139, NationalityCode = "FM" , NationalityName = "MICRONESIA, FEDERATED STATES OF", IsActive = 1 },
                 new Nationality { NationalityId = 140, NationalityCode = "MD" , NationalityName = "MOLDOVA, REPUBLIC OF", IsActive = 1 },
                 new Nationality { NationalityId = 141, NationalityCode = "MC" , NationalityName = "MONACO", IsActive = 1 },
                 new Nationality { NationalityId = 142, NationalityCode = "MN" , NationalityName = "MONGOLIA", IsActive = 1 },
                 new Nationality { NationalityId = 143, NationalityCode = "MS" , NationalityName = "MONTSERRAT", IsActive = 1 },
                 new Nationality { NationalityId = 144, NationalityCode = "MA" , NationalityName = "MOROCCO", IsActive = 1 },
                 new Nationality { NationalityId = 145, NationalityCode = "MZ" , NationalityName = "MOZAMBIQUE", IsActive = 1 },
                 new Nationality { NationalityId = 146, NationalityCode = "MM" , NationalityName = "MYANMAR", IsActive = 1 },
                 new Nationality { NationalityId = 147, NationalityCode = "NA" , NationalityName = "NAMIBIA", IsActive = 1 },
                 new Nationality { NationalityId = 148, NationalityCode = "NR" , NationalityName = "NAURU", IsActive = 1 },
                 new Nationality { NationalityId = 149, NationalityCode = "NP" , NationalityName = "NEPAL", IsActive = 1 },
                 new Nationality { NationalityId = 150, NationalityCode = "NL" , NationalityName = "NETHERLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 151, NationalityCode = "AN" , NationalityName = "NETHERLANDS ANTILLES", IsActive = 1 },
                 new Nationality { NationalityId = 152, NationalityCode = "NC" , NationalityName = "NEW CALEDONIA", IsActive = 1 },
                 new Nationality { NationalityId = 153, NationalityCode = "NZ" , NationalityName = "NEW ZEALAND", IsActive = 1 },
                 new Nationality { NationalityId = 154, NationalityCode = "NI" , NationalityName = "NICARAGUA", IsActive = 1 },
                 new Nationality { NationalityId = 155, NationalityCode = "NE" , NationalityName = "NIGER", IsActive = 1 },
                 new Nationality { NationalityId = 156, NationalityCode = "NG" , NationalityName = "NIGERIA", IsActive = 1 },
                 new Nationality { NationalityId = 157, NationalityCode = "NU" , NationalityName = "NIUE", IsActive = 1 },
                 new Nationality { NationalityId = 158, NationalityCode = "NF" , NationalityName = "NORFOLK ISLAND", IsActive = 1 },
                 new Nationality { NationalityId = 159, NationalityCode = "MP" , NationalityName = "NORTHERN MARIANA ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 160, NationalityCode = "NO" , NationalityName = "NORWAY", IsActive = 1 },
                 new Nationality { NationalityId = 161, NationalityCode = "OM" , NationalityName = "OMAN", IsActive = 1 },
                 new Nationality { NationalityId = 162, NationalityCode = "PK" , NationalityName = "PAKISTAN", IsActive = 1 },
                 new Nationality { NationalityId = 163, NationalityCode = "PW" , NationalityName = "PALAU", IsActive = 1 },
                 new Nationality { NationalityId = 164, NationalityCode = "PS" , NationalityName = "PALESTINIAN TERRITORY, OCCUPIED", IsActive = 1 },
                 new Nationality { NationalityId = 165, NationalityCode = "PA" , NationalityName = "PANAMA", IsActive = 1 },
                 new Nationality { NationalityId = 166, NationalityCode = "PG" , NationalityName = "PAPUA NEW GUINEA", IsActive = 1 },
                 new Nationality { NationalityId = 167, NationalityCode = "PY" , NationalityName = "PARAGUAY", IsActive = 1 },
                 new Nationality { NationalityId = 168, NationalityCode = "PE" , NationalityName = "PERU", IsActive = 1 },
                 new Nationality { NationalityId = 169, NationalityCode = "PH" , NationalityName = "PHILIPPINES", IsActive = 1 },
                 new Nationality { NationalityId = 170, NationalityCode = "PN" , NationalityName = "PITCAIRN", IsActive = 1 },
                 new Nationality { NationalityId = 171, NationalityCode = "PL" , NationalityName = "POLAND", IsActive = 1 },
                 new Nationality { NationalityId = 172, NationalityCode = "PT" , NationalityName = "PORTUGAL", IsActive = 1 },
                 new Nationality { NationalityId = 173, NationalityCode = "PR" , NationalityName = "PUERTO RICO", IsActive = 1 },
                 new Nationality { NationalityId = 174, NationalityCode = "QA" , NationalityName = "QATAR", IsActive = 1 },
                 new Nationality { NationalityId = 175, NationalityCode = "RE" , NationalityName = "REUNION", IsActive = 1 },
                 new Nationality { NationalityId = 176, NationalityCode = "RO" , NationalityName = "ROMANIA", IsActive = 1 },
                 new Nationality { NationalityId = 177, NationalityCode = "RU" , NationalityName = "RUSSIAN FEDERATION", IsActive = 1 },
                 new Nationality { NationalityId = 178, NationalityCode = "RW" , NationalityName = "RWANDA", IsActive = 1 },
                 new Nationality { NationalityId = 179, NationalityCode = "SH" , NationalityName = "SAINT HELENA", IsActive = 1 },
                 new Nationality { NationalityId = 180, NationalityCode = "KN" , NationalityName = "SAINT KITTS AND NEVIS", IsActive = 1 },
                 new Nationality { NationalityId = 181, NationalityCode = "LC" , NationalityName = "SAINT LUCIA", IsActive = 1 },
                 new Nationality { NationalityId = 182, NationalityCode = "PM" , NationalityName = "SAINT PIERRE AND MIQUELON", IsActive = 1 },
                 new Nationality { NationalityId = 183, NationalityCode = "VC" , NationalityName = "SAINT VINCENT AND THE GRENADINES", IsActive = 1 },
                 new Nationality { NationalityId = 184, NationalityCode = "WS" , NationalityName = "SAMOA", IsActive = 1 },
                 new Nationality { NationalityId = 185, NationalityCode = "SM" , NationalityName = "SAN MARINO", IsActive = 1 },
                 new Nationality { NationalityId = 186, NationalityCode = "ST" , NationalityName = "SAO TOME AND PRINCIPE", IsActive = 1 },
                 new Nationality { NationalityId = 187, NationalityCode = "SA" , NationalityName = "SAUDI ARABIA", IsActive = 1 },
                 new Nationality { NationalityId = 188, NationalityCode = "SN" , NationalityName = "SENEGAL", IsActive = 1 },
                 new Nationality { NationalityId = 189, NationalityCode = "CS" , NationalityName = "SERBIA AND MONTENEGRO", IsActive = 1 },
                 new Nationality { NationalityId = 190, NationalityCode = "SC" , NationalityName = "SEYCHELLES", IsActive = 1 },
                 new Nationality { NationalityId = 191, NationalityCode = "SL" , NationalityName = "SIERRA LEONE", IsActive = 1 },
                 new Nationality { NationalityId = 192, NationalityCode = "SG" , NationalityName = "SINGAPORE", IsActive = 1 },
                 new Nationality { NationalityId = 193, NationalityCode = "SK" , NationalityName = "SLOVAKIA", IsActive = 1 },
                 new Nationality { NationalityId = 194, NationalityCode = "SI" , NationalityName = "SLOVENIA", IsActive = 1 },
                 new Nationality { NationalityId = 195, NationalityCode = "SB" , NationalityName = "SOLOMON ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 196, NationalityCode = "SO" , NationalityName = "SOMALIA", IsActive = 1 },
                 new Nationality { NationalityId = 197, NationalityCode = "ZA" , NationalityName = "SOUTH AFRICA", IsActive = 1 },
                 new Nationality { NationalityId = 198, NationalityCode = "GS" , NationalityName = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 199, NationalityCode = "ES" , NationalityName = "SPAIN", IsActive = 1 },
                 new Nationality { NationalityId = 200, NationalityCode = "LK" , NationalityName = "SRI LANKA", IsActive = 1 },
                 new Nationality { NationalityId = 201, NationalityCode = "SD" , NationalityName = "SUDAN", IsActive = 1 },
                 new Nationality { NationalityId = 202, NationalityCode = "SR" , NationalityName = "SURINAME", IsActive = 1 },
                 new Nationality { NationalityId = 203, NationalityCode = "SJ" , NationalityName = "SVALBARD AND JAN MAYEN", IsActive = 1 },
                 new Nationality { NationalityId = 204, NationalityCode = "SZ" , NationalityName = "SWAZILAND", IsActive = 1 },
                 new Nationality { NationalityId = 205, NationalityCode = "SE" , NationalityName = "SWEDEN", IsActive = 1 },
                 new Nationality { NationalityId = 206, NationalityCode = "CH" , NationalityName = "SWITZERLAND", IsActive = 1 },
                 new Nationality { NationalityId = 207, NationalityCode = "SY" , NationalityName = "SYRIAN ARAB REPUBLIC", IsActive = 1 },
                 new Nationality { NationalityId = 208, NationalityCode = "TW" , NationalityName = "TAIWAN, PROVINCE OF CHINA", IsActive = 1 },
                 new Nationality { NationalityId = 209, NationalityCode = "TJ" , NationalityName = "TAJIKISTAN", IsActive = 1 },
                 new Nationality { NationalityId = 210, NationalityCode = "TZ" , NationalityName = "TANZANIA, UNITED REPUBLIC OF", IsActive = 1 },
                 new Nationality { NationalityId = 211, NationalityCode = "TH" , NationalityName = "THAILAND", IsActive = 1 },
                 new Nationality { NationalityId = 212, NationalityCode = "TL" , NationalityName = "TIMOR-LESTE", IsActive = 1 },
                 new Nationality { NationalityId = 213, NationalityCode = "TG" , NationalityName = "TOGO", IsActive = 1 },
                 new Nationality { NationalityId = 214, NationalityCode = "TK" , NationalityName = "TOKELAU", IsActive = 1 },
                 new Nationality { NationalityId = 215, NationalityCode = "TO" , NationalityName = "TONGA", IsActive = 1 },
                 new Nationality { NationalityId = 216, NationalityCode = "TT" , NationalityName = "TRINIDAD AND TOBAGO", IsActive = 1 },
                 new Nationality { NationalityId = 217, NationalityCode = "TN" , NationalityName = "TUNISIA", IsActive = 1 },
                 new Nationality { NationalityId = 218, NationalityCode = "TR" , NationalityName = "TURKEY", IsActive = 1 },
                 new Nationality { NationalityId = 219, NationalityCode = "TM" , NationalityName = "TURKMENISTAN", IsActive = 1 },
                 new Nationality { NationalityId = 220, NationalityCode = "TC" , NationalityName = "TURKS AND CAICOS ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 221, NationalityCode = "TV" , NationalityName = "TUVALU", IsActive = 1 },
                 new Nationality { NationalityId = 222, NationalityCode = "UG" , NationalityName = "UGANDA", IsActive = 1 },
                 new Nationality { NationalityId = 223, NationalityCode = "UA" , NationalityName = "UKRAINE", IsActive = 1 },
                 new Nationality { NationalityId = 224, NationalityCode = "AE" , NationalityName = "UNITED ARAB EMIRATES", IsActive = 1 },
                 new Nationality { NationalityId = 225, NationalityCode = "GB" , NationalityName = "UNITED KINGDOM", IsActive = 1 },
                 new Nationality { NationalityId = 226, NationalityCode = "US" , NationalityName = "UNITED STATES", IsActive = 1 },
                 new Nationality { NationalityId = 227, NationalityCode = "UM" , NationalityName = "UNITED STATES MINOR OUTLYING ISLANDS", IsActive = 1 },
                 new Nationality { NationalityId = 228, NationalityCode = "UY" , NationalityName = "URUGUAY", IsActive = 1 },
                 new Nationality { NationalityId = 229, NationalityCode = "UZ" , NationalityName = "UZBEKISTAN", IsActive = 1 },
                 new Nationality { NationalityId = 230, NationalityCode = "VU" , NationalityName = "VANUATU", IsActive = 1 },
                 new Nationality { NationalityId = 231, NationalityCode = "VE" , NationalityName = "VENEZUELA", IsActive = 1 },
                 new Nationality { NationalityId = 232, NationalityCode = "VN" , NationalityName = "VIET NAM", IsActive = 1 },
                 new Nationality { NationalityId = 233, NationalityCode = "VG" , NationalityName = "VIRGIN ISLANDS, BRITISH", IsActive = 1 },
                 new Nationality { NationalityId = 234, NationalityCode = "VI" , NationalityName = "VIRGIN ISLANDS, U.S.", IsActive = 1 },
                 new Nationality { NationalityId = 235, NationalityCode = "WF" , NationalityName = "WALLIS AND FUTUNA", IsActive = 1 },
                 new Nationality { NationalityId = 236, NationalityCode = "EH" , NationalityName = "WESTERN SAHARA", IsActive = 1 },
                 new Nationality { NationalityId = 237, NationalityCode = "YE" , NationalityName = "YEMEN", IsActive = 1 },
                 new Nationality { NationalityId = 238, NationalityCode = "ZM" , NationalityName = "ZAMBIA", IsActive = 1 },
                 new Nationality { NationalityId = 239, NationalityCode = "ZW" , NationalityName = "ZIMBABWE", IsActive = 1 }
                );
        }
    }
}
